# Generated by Django 4.2 on 2024-01-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_futbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abr', models.CharField(max_length=4)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
